### ISSUE TITLE
tracing script TODO

### ISSUE THREAD

**Issue by mr-martian** [SwatPhonLab/UltraTrace#1]
_Originally posted by @jonorthwash at 2018-01-12T16:12:40Z ([original issue](https://github.swarthmore.edu/PhonLab/dicom-annotator/issues/1))_

- [x] Better zoom functionality, including based on window resizing.
- [ ] Ability to read directly from dicom files (cf. how the dicom library is used in the [alignment script](https://github.swarthmore.edu/PhonLab/ultrasound-scripts/blob/master/alignUsAudio.py)) and TextGrid files (potentially given a directory or directory structure where they have similar names).
  - [x] Ability to play snippits of audio given aligned flac files too.
  - [x] metadata at participant level
  - [ ] measurements at recording level
  - [ ] tracking of percent completion at participant and recording level
- [x] Point editing capability:
  - [x] Turn delete into undo
  - [x] Make a way to select nodes, and delete them or move them around
- [x] Some sort of less disk-intensive auto-save?
- [x] Refactored ability to make multiple traces on the same image (e.g., "tongue" versus "palate", but with arbitrary names and probably a default)
- [ ] Integration of some [auto trace library](https://github.com/jjberry/Autotrace)?
- [ ] Integration with plotting script (which also needs to be refactored), to be able to preview as you go.

**Comment by mr-martian** [comment]
_Originally posted by @jonorthwash at 2018-01-12T18:22:30Z_

20150629171639.TextGrid has two tiers of frame times, both called "all frames".  The correct measure is somewhere in between the two.  Should be able to use [content2TextGrid.py](https://github.swarthmore.edu/PhonLab/ultrasound-scripts/blob/master/content2TextGrid.py) to shift [one of] them.

@BartholomaeusAstrum, could you remind us how to do that?

**Comment by mr-martian** [comment]
_Originally posted by @jonorthwash at 2018-01-13T02:07:29Z_

As @BartholomaeusAstrum comments, the functionality we're looking for is in `shift.py`.

**Comment by mr-martian** [comment]
_Originally posted by @jonorthwash at 2018-03-01T22:31:51Z_

For tomorrow:
- Document remaining issues as separate issues
- Take care of bug fixes first
- Document code as appropriate
- Continue as you see fit; when I show up we can reorient it a bit.

**Comment by mr-martian** [comment]
_Originally posted by @jonorthwash at 2018-03-26T17:36:08Z_

Is everything in this issue exported to other issues?  If so, we should link them all and close this one.

**Comment by mr-martian** [comment]
_Originally posted by @BartholomaeusAstrum at 2019-07-17T17:59:46Z_

Outdated.
