### ISSUE TITLE
Completion percentage tracker

### ISSUE THREAD

**Issue by mr-martian** [SwatPhonLab/UltraTrace#10]
_Originally posted by @keggsmurph21 at 2018-03-02T13:58:41Z ([original issue](https://github.swarthmore.edu/PhonLab/dicom-annotator/issues/10))_

Use the data in the textgrid tiers to track how complete each item (tier, file, directory) is (%).

**Comment by mr-martian** [comment]
_Originally posted by @jonorthwash at 2018-06-25T20:39:51Z_

Steps to get this working:
* [x] Get display of TextGrid tiers working (#7).
* [x] Number of frames annotated and total in all non-empty intervals for each tier.
* [ ] Implement some form of highlighting (by color of something).

**Comment by mr-martian** [comment]
_Originally posted by @BartholomaeusAstrum at 2019-07-17T17:44:56Z_

Closed by 1f5748768e00a356aa086cc21c4928fb7d333797
