### ISSUE TITLE
TextGrid manipulation meta issue

### ISSUE THREAD

**Issue by jonorthwash** [SwatPhonLab/UltraTrace#139]
- [ ] Facility for adding tiers (mainly interval, but also point).
- [ ] Facility for adding intervals (and points) in a tier.
- [ ] Facility for adjusting intervals.
- [ ] Facility for changing name ("mark") of intervals.
- [ ] Maybe some "locking" mechanism to avoid accidental changes.
