### ISSUE TITLE
wxPython redesign TODO

### ISSUE THREAD

**Issue by jonorthwash** [SwatPhonLab/UltraTrace#159]
* [x] General interface
  * [x] 2x2 layout
  * [x] Control Panel sections
* [ ] Files control
  * [x] display file names
  * [ ] selecting file names changes file
  * [ ] _display something other than filenames (#154)_
  * [ ] _show percentage annotated_
  * [ ] _filter by name_
  * [ ] _filter by matches in textgrid?_
  * [ ] _reload metadata button (#152)_
* [ ] Frames control
  * [ ] change with previous/next buttons
  * [ ] change by entering number
  * [ ] play/pause control (see Ultrasound and Audio panes)
* [ ] Layers control
  * [x] display layers
  * [ ] show/toggle default
  * [ ] show/adjust colour
  * [ ] show/toggle visibility
  * [ ] add layer
  * [ ] rename layer
  * [ ] remove layer
  * [ ] selected = current
* [ ] Ultrasound pane
  * [ ] (expand later)
* [ ] Audio+TextGrid pane
  * [x] show spectrogram
  * [ ] show TextGrids
  * [ ] click navigation in spectrogram and TextGrids
  * [ ] collapse tiers on scroll
  * [ ] _collapse spectrogram to waveform on scroll (#52)_
  * [ ] _create/edit TextGrids (#139)_
  * [ ] _audio track selection (#153)_
* [ ] Control
  * [ ] keyboard shortcuts
  * [ ] keyboard navigation

See #147 for original issue.  _italics_ are enhancements; everything else is basic functionality.

**Comment by jonorthwash** [comment]
Screenshot of work as it currently stands:

![Screenshot from 2023-03-25 14-04-04](https://user-images.githubusercontent.com/963849/227734053-d7e01b45-5a99-4029-ba7e-18ae2afe10c0.png)
